---
abstract: 'Core Ext.Direct implementation for Perl'
author:
  - 'Alex Tokarev <tokarev@cpan.org>'
build_requires:
  Test::More: '0.82'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: RPC-ExtDirect
no_index:
  directory:
    - t
    - inc
requires:
  Attribute::Handlers: '0.87'
  JSON: '2.0'
  perl: '5.006'
resources:
  bugtracker: http://github.com/nohuhu/RPC-ExtDirect/issues
  repository: http://github.com/nohuhu/RPC-ExtDirect
version: '3.01'
