--- #YAML:1.0
name:               RPC-ExtDirect
version:            2.14
abstract:           Ext.Direct implementation for Perl
author:
    - Alexander Tokarev <tokarev@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Attribute::Handlers:  0.87
    JSON:                 2.0
    perl:                 5.006
    Test::More:           0.48
    Test::Pod:            1.00
resources:
    bugtracker:  http://github.com/nohuhu/RPC-ExtDirect/issues
    repository:  http://github.com/nohuhu/RPC-ExtDirect
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
