---
abstract: 'Ext.Direct implementation for Perl'
author:
  - 'Alexander Tokarev <tokarev@cpan.org>'
build_requires:
  Test::More: 0
  Test::Pod: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RPC-ExtDirect
no_index:
  directory:
    - t
    - inc
requires:
  Attribute::Handlers: 0.87
  JSON: 2.0
  perl: 5.012
resources:
  bugtracker: http://github.com/nohuhu/RPC-ExtDirect/issues
  repository: http://github.com/nohuhu/RPC-ExtDirect
version: 2.02
